from nekosuneai.avatar_http_patch import install_avatar_http_patch
from nekosuneai.mcp_oauth_recovery import install_mcp_oauth_recovery
from nekosuneai.settings_dashboard_patch import install_settings_dashboard_patch
from nekosuneai.settings_backend_patch import install_settings_backend_patch
from nekosuneai.settings_dashboard_compat import install_settings_dashboard_compat
from nekosuneai.music_dashboard_patch import install_music_dashboard_patch
from nekosuneai.ytdlp_nightly_patch import install_ytdlp_nightly_patch
from nekosuneai.dashboard_runtime_fix_patch import install_dashboard_runtime_fix_patch
from nekosuneai.tts_busy_guard_patch import install_tts_busy_guard_patch
from nekosuneai.bridge_edge_voice_patch import install_bridge_edge_voice_patch
from nekosuneai.kinect_vision_patch import install_kinect_vision_patch
from nekosuneai.dashboard_tts_config_patch import install_dashboard_tts_config_patch
from nekosuneai.media_youtube_provider_patch import install_media_youtube_provider_patch

install_avatar_http_patch()
install_mcp_oauth_recovery()
install_settings_dashboard_patch()
install_settings_backend_patch()
install_settings_dashboard_compat()
install_music_dashboard_patch()
install_ytdlp_nightly_patch()
install_dashboard_runtime_fix_patch()
install_tts_busy_guard_patch()
install_bridge_edge_voice_patch()
install_kinect_vision_patch()
install_dashboard_tts_config_patch()
install_media_youtube_provider_patch()

from nekosuneai.launcher import main


if __name__ == "__main__":
    main()
